language: python

python:
    - 3.4
    - 3.6

install:
    - pip install pipenv -i https://pypi.doubanio.com/simple/
    - pipenv install -d

script:
    - make cov
    - make build

after_success:
    - codecov

deploy:
    provider: releases
    api_key:
        secure: ${GITHUB_TOKEN}
    file: dist/aiosqlite3-*.whl
    skip_cleanup: true
    on:
        tags: true
