language: python

python:
    - 3.5
    - 3.6

install:
    - pip install pipenv -i https://pypi.doubanio.com/simple/
    - pipenv --three
    - sed -i s/pypi.python.org/pypi.doubanio.com/g Pipfile
    - pipenv install -d
    - pipenv shell

script:
    - make test
    - make cov

after_success:
    - codecov